### ISSUE TITLE
Is it possible to use loginurl ?

### ISSUE THREAD

**Issue by athimannil** [hprobotic/react-telegram-login#14]
Telegram Bot API comes with https://core.telegram.org/bots/api#loginurl

Can we deal Receiving **authorization data**  with **react-telegram-login** component 

![image](https://user-images.githubusercontent.com/4364227/67080348-57626c80-f195-11e9-999e-effe8f498b0c.png)

**Comment by hprobotic** [comment]
Seem related to #19 ?
