### ISSUE TITLE
Option to specify auth url

### ISSUE THREAD

**Issue by brookmg** [hprobotic/react-telegram-login#17]
There seems to be no option to add the `data-auth-url` option to the widget in order to redirect the user to some other endpoint.

**Comment by Kutalia** [comment]
That's right. You can use my fork which adds this feature before it's merged:
https://github.com/Kutalia/react-telegram-login
`yarn add https://github.com/Kutalia/react-telegram-login`

**Comment by brookmg** [comment]
Thanks, @Kutalia. I was planning to do that but didn't have time. I will look at it.

**Comment by hprobotic** [comment]
Thank you for added this @Kutalia
