### ISSUE TITLE
Log out

### ISSUE THREAD

**Issue by iKethavel** [hprobotic/react-telegram-login#18]
Could you help me find way to logout user?

**Comment by hprobotic** [comment]
What do you mean. Logout from telegram or from your application?

**Comment by iKethavel** [comment]
Helo @hprobotic !
I'm talking about telegram logout, not instagram. In my app I store token from server, which i generate using telegram user auth data. And that works fine, I could delete token from localstorage and it's looks like user has been logged out. But, after this i also logging out from my real telegram account on telegram site, and in my app(when I'm trying to login again) I will not receive new popup with telegram login! It will use my old account, but currently I could be even logged in another account.
