### ISSUE TITLE
usePic={false} shows user pic instead of hiding.

### ISSUE THREAD

**Issue by poeti8** [hprobotic/react-telegram-login#6]
Passing `usePic={false}` shows the user pic instead of hiding it.
I wonder why are you using "not operator(!)" here?
https://github.com/hprobotic/react-telegram-login/blob/9d2bc5f66b92c4f1ca42fb0d2b6b52e42abd2d19/src/index.js#L19

I can fix this and add prop types but was hesitant because I saw you used `// @flow`. Although, you're not actually using flow and its package is not included in the package.json.

So if you don't mind I'll fix this issue and also add prop-types.

**Comment by hprobotic** [comment]
Hi @poeti8 
I really appreciate your effort on this issue. And please create a feel free to create a PR and we can fix.  💯 
We can completely remove `# @flow` from the index.js file. Because i'm using flowtype as a global variable so i have added flow for every single js file. 👍 
Thanks
John
