### ISSUE TITLE
Start React localhost not work with telegram login

### ISSUE THREAD

**Issue by tanmynguyen** [hprobotic/react-telegram-login#9]
Hi! 
I using MacOS for development React. And i can't use react telegram login. Who can help for me setup.

**Comment by hprobotic** [comment]
Hi Nguyen

Please have a look on our readme file. Find some help on setup virtual
domain by edit hosts file from google search

**Comment by hprobotic** [comment]
If you edit your etc/hosts file you can assign an arbitrary hostname to be set to 127.0.0.1. Open up /etc/hosts in your favorite text editor and add this line:

`127.0.0.1   www.example.com`
Unsure of how to avoid specifying the port in the HTTP requests you make to example.com, but if you must avoid specifying that at the request level, you could run nodejs as root to make it listen on port 80.

Edit: After editing /etc/hosts, you may already have the DNS request for that domain cached. You can clear the cached entry by running this on the command line.

`dscacheutil -flushcache`
